# Generated by Django 5.1.1 on 2024-10-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_adminuser_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
