# Generated by Django 5.1 on 2024-08-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_email',
            field=models.EmailField(default='no-reply@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=20),
        ),
    ]
