# Generated by Django 5.1 on 2024-08-15 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_guest_email_booking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.table'),
        ),
    ]
