# Generated by Django 5.1.1 on 2024-10-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_guest_email_alter_booking_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='alerigies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
